name        : xf86bigfontproto
version     : 1.2.0
release     : 4
source      :
    - http://xorg.freedesktop.org/releases/individual/proto/xf86bigfontproto-1.2.0.tar.gz : d190e6462b2bbbac6ee9a007fb8eccb9ad9f5f70544154f388266f031d4bbb23
license     :
    - MIT
summary     : xf86bigfontproto X Extension
component   : xorg.proto
patterns    : /
description : |
    xf86bigfontproto X Extension
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
